---
title: "examples for GwR chapter 8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here's some of the code from [Chapter 8: Making maps with R](https://geocompr.robinlovelace.net/adv-map.html), for you to follow along with as we go through it in class.

```{r}
library(sf)
library(raster)
library(dplyr)
library(spData)
library(spDataLarge)
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package
```

## 8.2.1 tmap basics

```{r}
plot(nz)
nz
```

```{r}
# Add fill layer to nz shape
tm_shape(nz) +
  tm_fill() 
# Add border layer to nz shape
tm_shape(nz) +
  tm_borders() 
# Add fill and border layers to nz shape
tm_shape(nz) +
  tm_fill() +
  tm_borders() 

tm_shape(nz) +
  tm_polygons()
```

```{r}
qtm(nz) +
  qtm(nz_height)
```

## 8.2.2 Map objects

```{r}
map_nz = tm_shape(nz) +
  tm_polygons()
class(map_nz)

map_nz
```

```{r}
map_nz1 = map_nz +
  tm_shape(nz_elev) +
  tm_raster(alpha = 0.7)

map_nz1
```

```{r}
nz_water = st_union(nz) %>%
  st_buffer(22200) %>% 
  st_cast(to = "LINESTRING")

plot(nz_water)
```

```{r}
map_nz2 = map_nz1 +
  tm_shape(nz_water) +
  tm_lines()

map_nz2
```

```{r}
map_nz3 = map_nz2 +
  tm_shape(nz_height) +
  tm_dots()

map_nz3
```

```{r}
tmap_arrange(map_nz1, map_nz2, map_nz3)
```

## 8.2.3 Aesthetics

```{r}
ma1 = tm_shape(nz) + tm_fill(col = "red")
ma2 = tm_shape(nz) + tm_fill(col = "red", alpha = 0.3)
ma3 = tm_shape(nz) + tm_borders(col = "blue")
ma4 = tm_shape(nz) + tm_borders(lwd = 3)
ma5 = tm_shape(nz) + tm_borders(lty = 2)
ma6 = tm_shape(nz) + tm_fill(col = "red", alpha = 0.3) +
  tm_borders(col = "blue", lwd = 3, lty = 2)

tmap_arrange(ma1, ma2, ma3, ma4, ma5, ma6)
```

```{r}
plot(st_geometry(nz), col = nz$Land_area)  # works
# tm_shape(nz) + tm_fill(col = nz$Land_area) # fails
tm_shape(nz) + tm_fill(col = "Land_area")
```

```{r}
legend_title = expression("Area (km"^2*")")
map_nza = tm_shape(nz) +
  tm_fill(col = "Land_area", title = legend_title) + tm_borders()

map_nza
```

## 8.2.4 Color settings

```{r}
tm_shape(nz) + tm_polygons(col = "Median_income")
breaks = c(0, 3, 4, 5) * 10000
tm_shape(nz) + tm_polygons(col = "Median_income", breaks = breaks)
tm_shape(nz) + tm_polygons(col = "Median_income", n = 10)
tm_shape(nz) + tm_polygons(col = "Median_income", palette = "BuGn")
```

```{r}
tm_shape(nz) + tm_polygons("Population", palette = "Blues")
tm_shape(nz) + tm_polygons("Population", palette = "YlOrBr")
```

## 8.2.5 Layouts

```{r}
map_nz + 
  tm_compass(type = "8star", position = c("left", "top")) +
  tm_scale_bar(breaks = c(0, 100, 200), text.size = 1)
```

```{r}
map_nz + tm_layout(title = "New Zealand")
map_nz + tm_layout(scale = 5)
map_nz + tm_layout(bg.color = "lightblue")
map_nz + tm_layout(frame = FALSE)
```

```{r}
map_nza + tm_layout(frame.lwd = 5)
map_nza + tm_layout(inner.margins = 0.2)
map_nza + tm_layout(legend.show = FALSE)
map_nza + tm_layout(legend.position = c("right","bottom"))
```

```{r}
map_nza + tm_style("bw")
map_nza + tm_style("classic")
map_nza + tm_style("cobalt")
map_nza + tm_style("col_blind")
```

## 8.2.6 Faceted maps

```{r}
urb_1970_2030 = urban_agglomerations %>% 
  filter(year %in% c(1970, 1990, 2010, 2030))

tm_shape(world) +
  tm_polygons() +
  tm_shape(urb_1970_2030) +
  tm_symbols(col = "black", border.col = "white", size = "population_millions") +
  tm_facets(by = "year", nrow = 2, free.coords = FALSE)
```

8.2.7 Inset maps

```{r}
nz_region = st_bbox(c(xmin = 1340000, xmax = 1450000,
                      ymin = 5130000, ymax = 5210000),
                    crs = st_crs(nz_height)) %>%
  st_as_sfc()

nz_region
```

```{r}
nz_height_map = tm_shape(nz_elev, bbox = nz_region) +
  tm_raster(style = "cont", palette = "YlGn", legend.show = TRUE) +
  tm_shape(nz_height) +
  tm_symbols(shape = 2, col = "red", size = 1) +
  tm_scale_bar(position = c("left", "bottom"))

nz_height_map
```

```{r}
nz_map = tm_shape(nz) +
  tm_polygons() +
  tm_shape(nz_height) +
  tm_symbols(shape = 2, col = "red", size = 0.1) + 
  tm_shape(nz_region) +
  tm_borders(lwd = 3)

nz_map
```

```{r}
library(grid)

nz_height_map
print(nz_map, vp = viewport(0.8, 0.27, width = 0.5, height = 0.5))
```

```{r}
us_states_map = tm_shape(us_states, projection = 2163) +
  tm_polygons() + 
  tm_layout(frame = FALSE)

us_states_map
```

```{r}
hawaii_map = tm_shape(hawaii) +
  tm_polygons() + 
  tm_layout(title = "Hawaii", frame = FALSE, bg.color = NA, 
            title.position = c("LEFT", "BOTTOM"))

alaska_map = tm_shape(alaska) +
  tm_polygons() + 
  tm_layout(title = "Alaska", frame = FALSE, bg.color = NA)

hawaii_map
alaska_map
```

```{r}
us_states_map
print(hawaii_map, vp = grid::viewport(0.35, 0.1, width = 0.2, height = 0.1))
print(alaska_map, vp = grid::viewport(0.15, 0.15, width = 0.3, height = 0.3))
```
